name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Docker Compose
        run: |
          docker-compose up -d
          
      - name: Run tests
        run: |
          # Replace this with commands to run your tests
          echo "Running tests..."
        
      - name: Stop Docker Compose
        run: |
          docker-compose down

      - name: Clean up
        run: |
          docker system prune -f
